name: Periodic mz-clusterctl

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      mode:
        description: 'Operation mode'
        required: false
        default: 'dry-run'
        type: choice
        options:
          - dry-run
          - apply
      verbosity:
        description: 'Verbosity level'
        required: false
        default: '-vv'
        type: choice
        options:
          - '-v'
          - '-vv'
      cluster:
        description: 'Cluster to use for executing commands'
        required: false
        type: string
      create-replica:
        description: 'Create temporary replica with size (requires cluster)'
        required: false
        type: string
      filter-clusters:
        description: 'Limit to clusters matching this name regex'
        required: false
        type: string

jobs:
  clusterctl:
    runs-on: ubuntu-latest

    steps:
      - name: Run mz-clusterctl
        uses: materializeinc/mz-clusterctl@v2
        with:
          database-url: ${{ secrets.MATERIALIZE_DATABASE_URL }}
          mode: ${{ inputs.mode || 'apply' }}
          verbosity: ${{ inputs.verbosity || '-vv' }}
          cluster: ${{ inputs.cluster }}
          create-replica: ${{ inputs.create-replica }}
          filter-clusters: ${{ inputs.filter-clusters }}
          python-version: '3.12'
