# An example action that doesn't use our composite action. You can use this if
# you clone the complete repo, maybe because you need complete control over the
# code that runs.

name: Periodic mz-clusterctl

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Cluster to use for executing commands'
        required: false
        type: string
      create-replica:
        description: 'Create temporary replica with size (requires cluster)'
        required: false
        type: string

jobs:
  clusterctl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Run mz-clusterctl (apply)
        env:
          DATABASE_URL: ${{ secrets.MATERIALIZE_DATABASE_URL }}
        run: |
          ARGS="apply -vv"
          if [ -n "${{ inputs.cluster }}" ]; then
            ARGS="$ARGS --cluster ${{ inputs.cluster }}"
          fi
          if [ -n "${{ inputs.create-replica }}" ]; then
            ARGS="$ARGS --create-replica ${{ inputs.create-replica }}"
          fi
          uv run mz-clusterctl $ARGS
